services:

  db: 
    image: postgres:latest
    container_name: postgress_poc
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ease_queue_db
      POSTGRES_USER: ease_queue_user
      POSTGRES_PASSWORD: ease_queue_pass
    ports:
      - "5432:5432"
    networks:
      - ease_network
      
  adminer:
    image: adminer
    container_name: adminer_poc
    restart: always
    ports:
      - 8085:8080
    networks:
      - ease_network
  redis:
    image: redis:8.10-alpine
    container_name: redis_poc
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ease_network
  mongo: 
    image: mongo:8.3.11
    container_name: mongo_poc
    restart: unless-stopped
    ports:
      - "${MONGO_INITDB_ROOT_PORT:-27017}:27017"
    volumes:
      - mongo_poc_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-ease_mongo_usr}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-ease_mongo_pass}" 
volumes:
  mongo_poc_vol:

networks:
  ease_network:
    driver: bridge