INSERT INTO clients (
    name,
    email,
    address
) VALUES
    ('Client 1', 'client-1@mail.com', 'Address 1, distric 1'),
    ('Client 2', 'client-2@mail.com', 'Address 2, distric 2'),
    ('Client 3', 'client-3@mail.com', 'Address 3, distric 3'),
    ('Client 4', 'client-4@mail.com', 'Address 4, distric 4'),
    ('Client 5', 'client-5@mail.com', 'Address 5, distric 5'),
    ('Client 6', 'client-6@mail.com', 'Address 6, distric 6'),
    ('Client 7', 'client-7@mail.com', 'Address 7, distric 7'),
    ('Client 8', 'client-8@mail.com', 'Address 8, distric 8'),
    ('Client 9', 'client-9@mail.com', 'Address 9, distric 9'),
    ('Client 10', 'client-10@mail.com', 'Address 10, distric 10'),
    ('Client 11', 'client-11@mail.com', 'Address 11, distric 11'),
    ('Client 12', 'client-12@mail.com', 'Address 2, distric 12'),
    ('Client 13', 'client-13@mail.com', 'Address 3, distric 13'),
    ('Client 14', 'client-14@mail.com', 'Address 4, distric 14'),
    ('Client 15', 'client-15@mail.com', 'Address 5, distric 15'),
    ('Client 16', 'client-16@mail.com', 'Address 6, distric 16'),
    ('Client 17', 'client-17@mail.com', 'Address 7, distric 17'),
    ('Client 18', 'client-18@mail.com', 'Address 8, distric 18'),
    ('Client 19', 'client-19@mail.com', 'Address 9, distric 19'),
    ('Client 20', 'client-20@mail.com', 'Address 20, distric 20'),
    ('Client 21', 'client-21@mail.com', 'Address 21, distric 21'),
    ('Client 22', 'client-22@mail.com', 'Address 22, distric 22'),
    ('Client 23', 'client-23@mail.com', 'Address 23, distric 23'),
    ('Client 24', 'client-24@mail.com', 'Address 24, distric 24'),
    ('Client 25', 'client-25@mail.com', 'Address 25, distric 25'),
    ('Client 26', 'client-26@mail.com', 'Address 26, distric 26'),
    ('Client 27', 'client-27@mail.com', 'Address 27, distric 27'),
    ('Client 28', 'client-28@mail.com', 'Address 28, distric 28'),
    ('Client 29', 'client-29@mail.com', 'Address 29, distric 29');